security:
    encoders:
        STMS\STMSBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        database_users:
          entity: { class: STMSBundle:User, property: email }

    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login
                success_handler: authentication_handler
                failure_handler: authentication_handler
            logout:
                path:   logout
                target: index
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }